[package]
name = "buildwise-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
openai-api-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
